name: Github Action Demo
on: [push]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome Message
        run: echo "Welcome to Github Action Workflows"
      - name: checking with LS
        run: ls ${{ github.workspace }}
     
